### ISSUE TITLE
npm install fails on Windows 10

### ISSUE THREAD

**Issue by Cleanshooter** [juliancwirko/react-npm-boilerplate#3]
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> react-npm-boilerplate@1.0.0 prepublish C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid
> babel --plugins 'transform-es2015-modules-umd' src --ignore __tests__ --out-dir ./dist

ReferenceError: Unknown plugin "'transform-es2015-modules-umd'" specified in "base" at 0, attempted to resolve relative to "src"
    at C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-core\lib\transformation\file\options\option-manager.js:176:17
    at Array.map (native)
    at Function.normalisePlugins (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-core\lib\transformation\file\options\option-manager.js:154:20)
    at OptionManager.mergeOptions (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:36)
    at OptionManager.init (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-core\lib\transformation\file\options\option-manager.js:374:12)
    at File.initOptions (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-core\lib\transformation\file\index.js:216:65)
    at new File (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-core\lib\transformation\file\index.js:139:24)
    at Pipeline.transform (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-core\lib\transformation\pipeline.js:46:16)
    at transform (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-cli\lib\babel\util.js:50:22)
    at Object.compile (C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\node_modules\babel-cli\lib\babel\util.js:59:12)

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Moto\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE
npm ERR! react-npm-boilerplate@1.0.0 prepublish: `babel --plugins 'transform-es2015-modules-umd' src --ignore __tests__ --out-dir ./dist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-npm-boilerplate@1.0.0 prepublish script 'babel --plugins 'transform-es2015-modules-umd' src --ignore __tests__ --out-dir ./dist'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-npm-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     babel --plugins 'transform-es2015-modules-umd' src --ignore __tests__ --out-dir ./dist
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-npm-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-npm-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Moto\Documents\Projects\Mark\material-ui-layout\material-layout\material-grid\npm-debug.log

**Comment by juliancwirko** [comment]
Hi, are you sure that you have `babel-plugin-transform-es2015-modules-umd` installed in your `node_modules` ?

**Comment by MartinDawson** [comment]
Throws for me too on windows 7. I have to remove this line from package.json prepublish:
`--plugins 'transform-es2015-modules-umd`.

I specified it in the babelrc file instead as recommended [here](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-umd) but I am not sure if this is correct.

**Comment by juliancwirko** [comment]
Hi could you try now? It seems like this pr [#4](https://github.com/juliancwirko/react-npm-boilerplate/pull/4) helps, but I can't test it on Windows right now. Thanks!

**Comment by juliancwirko** [comment]
I'll close it for now. It will be rebuilded using Rollup
